CREATE TABLE Products(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(25) UNIQUE NOT NULL,
Description NVARCHAR(255) NOT NULL,
Recipe NVARCHAR(MAX) NOT NULL,
Price MONEY
)

CREATE TABLE Countries(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(50) UNIQUE
)

CREATE TABLE Distributors(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(25) UNIQUE NOT NULL,
AddressText NVARCHAR(30) NOT NULL,
Summary NVARCHAR(200) NOT NULL,
CountryId INT FOREIGN KEY
REFERENCES Countries (Id)
)

CREATE TABLE Customers(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(25) NOT NULL,
LastName NVARCHAR(25) NOT NULL,
Gender CHAR(1) CHECK(Gender = 'M' OR Gender = 'F'),
Age INT NOT NULL,
PhoneNumber CHAR(10) CHECK (DATALENGTH(PhoneNumber) = 10),
CountryId INT FOREIGN KEY
REFERENCES Countries (Id)
)

CREATE TABLE Feedbacks(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Description NVARCHAR(255) NOT NULL,
Rate NUMERIC(2,2),
ProductId INT FOREIGN KEY
REFERENCES Products (Id),
CustomerId INT FOREIGN KEY
REFERENCES Customers (Id)
)

CREATE TABLE Ingredients(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(30) NOT NULL,
Description NVARCHAR(200) NOT NULL,
OriginCountryId INT FOREIGN KEY
REFERENCES Countries (Id),
DistributorId INT FOREIGN KEY
REFERENCES Distributors (Id)
)

CREATE TABLE ProductsIngredients(
ProductId INT FOREIGN KEY
REFERENCES Products (Id),
IngredientId INT FOREIGN KEY
REFERENCES Ingredients (Id)
)